### ISSUE TITLE
Plot does not look right when using vnc or x-forwarding

### ISSUE THREAD

**Issue by aashish24** [CDAT/vcs#39]
@danlipsa @doutriaux1

**Comment by durack1** [comment]
@aashish24 I use VNC, so would be happy to provide feedback if there was something to provide feedback on.. the issue above doesn't have much (if any) detail to respond to..

**Comment by aashish24** [comment]
thanks @durack1 what was reported that: 

1. Using VNC on certain systems (Mac) the rendering looks distorted or broken somehow

2. Using X forwarding on some systems, the bg=0 produces blank black plot

Accoring to @danlipsa the issue is with GL on the server end and he recommended using VirtualGL on the server in these cases. He sent a rough instructions to @doutriaux1. 


@danlipsa could  you post same instructions on wiki?

**Comment by durack1** [comment]
@aashish24 I can confirm that in the case of VNC I have had problems writing to png files in foreground mode, as it appears a screen scrape occurs rather than some backing store version of the graphic being written to the file. The `bg=1` also seemed to have a nasty memory leak that rendered batch usage impossible for me - see UV-CDAT/uvcdat#1424 and some of the other linked issues

**Comment by doutriaux1** [comment]
@durack1 I believe/thought/hoped the `bg=True` memory leak issue was sloved now. @aashish24, @danlipsa ?

**Comment by danlipsa** [comment]
It should be:
https://github.com/UV-CDAT/uvcdat/issues/1397
