### ISSUE TITLE
downloading a jupyter notebook has html does not have the image/plot included

### ISSUE THREAD

**Issue by muryanto1** [CDAT/vcs#424]
@davis278 found the issue.

To reproduce the problem:
conda create -n just_vcs -c cdat/label/nightly -c conda-forge vcs jupyter "libnetcdf=4.6.2" "python=3.7"
source activate just_vcs
jupyter notebook

open a notebook for the kernel for this env, and run the following in the notebook cells:
```
import vcs
import cdms2
vcs.download_sample_data_files()
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt")
x=vcs.init(bg=True)
x.plot(s)
```

you should see a plot.
click on 'File' tab, and hover over to 'Download as', and select 'HTML', it should download the notebook as html, and viewing the html in a browser should show the plot, but it does not.

**Comment by forsyth2** [comment]
`git bisect` shows us that this bug is introduced in https://github.com/CDAT/vcs/commit/ff4041433a6b3048450c25e3dac7cfa5a5333d3c.

Using the IPythonDisplay class instead of VBox (as was done before the above commit), Jupyter's "Download as [html]" button does produce a plot in the html. 

See https://github.com/CDAT/vcs/commit/ff4041433a6b3048450c25e3dac7cfa5a5333d3c#diff-02aa09a23b993d556845f5e24e1706c6R325. Setting `widgets = []` on that line still does not result in the plot displaying in the html. This implies using VBox itself, not something in `widgets`, is causing the error.

Interestingly, `jupyter nbconvert --execute --to html <notebook>` does produce the desired result. It shows the plot in the html along with the slider. (The slider can be toggled but this does not change the plot. According to https://nbconvert.readthedocs.io/en/latest/usage.html#convert-html the plot should be static in the html version.)

**Comment by forsyth2** [comment]
Added 
Running `jupyter nbconvert --execute --to html <notebook>` on the example with cleared output

**Comment by forsyth2** [comment]
Added the following two lines to the example notebook above.
```
import nbconvert
print(nbconvert.__version__)
```
Running `jupyter nbconvert --execute --to html <notebook>` on this with cleared output prints `5.6.1` and also displays the plot in html. Running the notebook on the web server and clicking "Download as" also prints `5.6.1` yet it does _not_ display the plot in the html.

**Comment by forsyth2** [comment]
Running the Jupyter notebook and then `jupyter nbconvert --execute --to html <notebook>` (no `--execute`) appears to be equivalent to clicking "Download as" > "HTML". That is, no plot is displayed. This implies that if `nbconvert` executes, then the plot is displayed properly, but if the Jupyter Notebooks executes, then the plot is _not_ displayed properly.

Since the static plot did display properly, one possible solution would be to display the static plot (IPythonDisplay, not the VBox widget) if converting to HTML. However, I'm only seeing ways to remove output when converting (https://nbconvert.readthedocs.io/en/latest/removing_cells.html) - not ways to _change_ the output (i.e. from VBox to IPythonDisplay) when converting.
